name: painter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.5.0
  path_drawing: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  shaders:
    - assets/shaders/simple_shader.frag
    - assets/shaders/complex_shader.frag

  assets:
    - assets/images/
